version: '3.8'
services:
  server-test:
    container_name: server-name
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
